GTC-3437: Use actual lambda layers in tests; improve test failure detection; fix a few bugs (#110)
* Pin TF version; bump AWS provider version to 5 to allow for newer Python lambdas
* Use actual lambda layers for tests instead of installing another set of packages
* Fix uses of str,Enum for Python 3.11+
* Use latest TF module
* Pin GHA runs-on image
* Clean caches on install
* Load lambda layer libs before system ones
* Download, use lambda layers for tests
* Make test failures more visible
* Be more defensive when accessing DynamoDB
* Add pyproject.toml to obsolete setup.py, pytest.ini; requirements files
* Change some log statements to debug only
* Fix filtering for success regardless of passed filter

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -4,8 +4,29 @@ set -e
 
 docker compose -f docker/terraform/docker-compose.yml build
 
-pip install -e .
-pip install -r requirements-dev.txt
+PYTHON_VERSION="3.10"
+VIRTUAL_ENV="${VIRTUAL_ENV:-.venv_uv}"
+
+# Install Python and create the venv all in one go
+if command -v "uv" >/dev/null 2>&1; then
+  echo "uv (needed to create venv) found in path"
+else
+  echo "uv (needed to create venv) NOT found in path"
+  echo "If uv is installed, add its binary directory to your path and try "
+  echo "running setup script again. For example: "
+  echo "'PATH=\$PATH:~/bin ./scripts/setup' for uv installed in ~/bin"
+  echo "Otherwise, see https://docs.astral.sh/uv/getting-started/installation/"
+  exit 1
+fi
+uv venv ${VIRTUAL_ENV} --python ${PYTHON_VERSION} --seed
+. ${VIRTUAL_ENV}/bin/activate
+
+# Now install all raster analysis dev deps in the venv
+echo "Installing deps into venv"
+uv sync --locked --active --all-extras
+
+echo "Installing pre-commit hooks"
+pre-commit install
+pre-commit
 
 detect-secrets scan > .secrets.baseline
-pre-commit install
